# Sales Records Analysis
### Author: Will Poindexter
### Exercise 2.E Using functions for analyzing data

This notebook analyzes a small sales dataset using Python functions.
Each function takes the full dataset as its first argument.

In [8]:
sales_data = [
    ('Laptop', 'East', 1200.00),
    ('Phone', 'West', 850.00),
    ('Tablet', 'East', 400.00),
    ('Monitor', 'South', 650.00),
    ('Keyboard', 'West', 75.00),
    ('Laptop', 'South', 1150.00),
    ('Phone', 'East', 900.00),
    ('Tablet', 'West', 425.00),
    ('Monitor', 'East', 680.00),
    ('Keyboard', 'South', 80.00),
    ('Laptop', 'West', 1300.00),
    ('Phone', 'West', 820.00),
]

## Lab 1. Total sales by region

In [9]:
def region_total(data, region):
    return sum(amt for _, r, amt in data if r == region)

In [10]:
print(region_total(sales_data, 'East'))
print(region_total(sales_data, 'West'))
print(region_total(sales_data, 'South'))

3180.0
3470.0
1880.0


## Lab 2. Count of sales by region

In [11]:
def region_count(data, region):
    return sum(1 for _, r, _ in data if r == region)

In [12]:
print(region_count(sales_data, 'East'))
print(region_count(sales_data, 'West'))
print(region_count(sales_data, 'South'))

4
5
3


## Lab 3. Average sale amount by region

In [13]:
def region_average(data, region):
    count = region_count(data, region)

    if count == 0:
        return 0

    return region_total(data, region) / count

In [14]:
print(region_average(sales_data, 'East'))
print(region_average(sales_data, 'West'))
print(region_average(sales_data, 'South'))
print(region_average(sales_data, 'North'))

795.0
694.0
626.6666666666666
0


## Lab 4. Filter by sale amount

In [15]:
def sales_above(data, threshold):
    return [sale for sale in data if sale[2] > threshold]

In [16]:
results = sales_above(sales_data, 500)

for sale in results:
    print(sale)

('Laptop', 'East', 1200.0)
('Phone', 'West', 850.0)
('Monitor', 'South', 650.0)
('Laptop', 'South', 1150.0)
('Phone', 'East', 900.0)
('Monitor', 'East', 680.0)
('Laptop', 'West', 1300.0)
('Phone', 'West', 820.0)


## Lab 5. Top and Bottom Sale

In [17]:
def top_sale(data):
    return max(data, key=lambda s: s[2])

def bottom_sale(data):
    return min(data, key=lambda s: s[2])

In [18]:
print("Top Sale:")
print(top_sale(sales_data))

print()

print("Bottom Sale:")
print(bottom_sale(sales_data))

Top Sale:
('Laptop', 'West', 1300.0)

Bottom Sale:
('Keyboard', 'West', 75.0)


The top sale was a Laptop in the West region for $1300.00.
The bottom sale was a Keyboard in the West region for $75.00.

## Lab 6. Apply a Discount

In [19]:
def apply_discount(data, discount_pct):
    return list(
        map(
            lambda s: (s[0], s[1], s[2] * (1 - discount_pct)),
            data))

In [20]:
discounted_sales = apply_discount(sales_data, 0.15)

print("Original:")
for sale in sales_data[:3]:
    print(sale)

print()

print("Discounted:")
for sale in discounted_sales[:3]:
    print(sale)

Original:
('Laptop', 'East', 1200.0)
('Phone', 'West', 850.0)
('Tablet', 'East', 400.0)

Discounted:
('Laptop', 'East', 1020.0)
('Phone', 'West', 722.5)
('Tablet', 'East', 340.0)


## Lab 7. Unique Regions

In [21]:
 def unique_regions(data):
    return sorted(set(region for _, region, _ in data))

In [22]:
print(unique_regions(sales_data))

['East', 'South', 'West']


This function is useful because it identifies all unique regions in a dataset without duplicates. In a larger analysis program, it could be used to automatically generate reports, summaries, or visualizations for each region without manually entering region names.

## Lab 8. Region Summary

In [25]:
def region_summary(data, region):
    region_data = [sale for sale in data if sale[1] == region]

    total = region_total(data, region)
    count = region_count(data, region)
    average = region_average(data, region)
    top = top_sale(region_data)

    print(f"{region} Region")
    print(f"Records: {count}")
    print(f"Total Sales: ${total:.2f}")
    print(f"Average Sale: ${average:.2f}")
    print(f"Top Sale: {top[0]} - ${top[2]:.2f}")

In [26]:
region_summary(sales_data, "East")

East Region
Records: 4
Total Sales: $3180.00
Average Sale: $795.00
Top Sale: Laptop - $1200.00


## Lab 9. Full Summary

In [27]:
for region in unique_regions(sales_data):
    region_summary(sales_data, region)
    print()

East Region
Records: 4
Total Sales: $3180.00
Average Sale: $795.00
Top Sale: Laptop - $1200.00

South Region
Records: 3
Total Sales: $1880.00
Average Sale: $626.67
Top Sale: Laptop - $1150.00

West Region
Records: 5
Total Sales: $3470.00
Average Sale: $694.00
Top Sale: Laptop - $1300.00



In this lab, I learned how to use functions to analyze a sales dataset. I practiced calculating totals, counts, averages, filtering records, finding top and bottom sales, applying discounts, and creating summaries by region. This helped me understand how functions make analysis more organized and reusable.